# This rule is not used by the project new-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to flashbot.example.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: new-operator
    app.kubernetes.io/managed-by: kustomize
  name: mycustomresource-viewer-role
rules:
- apiGroups:
  - flashbot.example.com
  resources:
  - mycustomresources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - flashbot.example.com
  resources:
  - mycustomresources/status
  verbs:
  - get
