# This rule is not used by the project new-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over flashbot.example.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: new-operator
    app.kubernetes.io/managed-by: kustomize
  name: mycustomresource-admin-role
rules:
- apiGroups:
  - flashbot.example.com
  resources:
  - mycustomresources
  verbs:
  - '*'
- apiGroups:
  - flashbot.example.com
  resources:
  - mycustomresources/status
  verbs:
  - get
