---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - flashbot.example.com
  resources:
  - mycustomresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - flashbot.example.com
  resources:
  - mycustomresources/finalizers
  verbs:
  - update
- apiGroups:
  - flashbot.example.com
  resources:
  - mycustomresources/status
  verbs:
  - get
  - patch
  - update
