apiVersion: flashbot.example.com/v1
kind: MyCustomResource
metadata:
  labels:
    app.kubernetes.io/name: new-operator
    app.kubernetes.io/managed-by: kustomize
  name: mycustomresource-sample
spec:
  # TODO(user): Add fields here
